### ISSUE TITLE
NumberWrite bug

### ISSUE THREAD

**Issue by Mobivlad** [RomanMalyi/STM32F4#1]
The function generates an array with digits of the number. And, for example, if we send 0 to LCD, LCD will show chr(0), not '0', and it will now show 0 at lcd. 
https://github.com/RomanMalyi/STM32F4/blob/791d308e7715c658f1035c410f50500a584c4f88/src/LCD/Src/main.c#L47

**Comment by RomanMalyi** [comment]
Fixed
