### ISSUE TITLE
Program loop work

### ISSUE THREAD

**Issue by Mobivlad** [RomanMalyi/STM32F4#2]
On pins, where buttons are connected there is a HIGH level without a button push.
![image](https://user-images.githubusercontent.com/17147322/77543999-1ba0a100-6eb1-11ea-9e97-e52206c34ae9.png)

https://github.com/RomanMalyi/STM32F4/blob/791d308e7715c658f1035c410f50500a584c4f88/src/LCD/Src/main.c#L39-L41

**Comment by RomanMalyi** [comment]
Fixed
